import assert from "node:assert/strict";
import { FifoRepository } from "./fifo-repository.js";
class DatabaseMock { constructor(){ this.queries = []; this.transactions = []; } async query(sql, bind = []){ this.queries.push({ sql, bind }); if (sql.includes("SELECT id FROM")) return []; if (sql.includes("COUNT(*)")) return [{ count: 0 }]; if (sql.includes("accounting_fifo_runs")) return [{ id: 1, status: "running", metrics_json: "{}" }]; return []; } async transaction(statements){ this.transactions.push(statements); } }
const database = new DatabaseMock(); const repository = new FifoRepository(database);
await repository.startRun({ fifoVersion: 1, sourceCostLotVersion: 1, sourceLedgerVersion: 1, startedAt: 123 });
const startStatements = database.transactions.at(-1);
assert.equal(startStatements.length, 2);
assert.match(startStatements[0].sql, /status = 'failed'/);
assert.match(startStatements[0].sql, /status = 'running'/);
assert.match(startStatements[1].sql, /INSERT INTO accounting_fifo_runs/);
const demand = { id: "d1", fifoVersion: 1, sourceCostLotVersion: 1, sourceLedgerVersion: 1, sourceLedgerTransactionId: "t1", sourceLedgerLineId: "line1", sourceProjectionId: "p1", sourceCanonicalEventId: "c1", itemId: "1", itemUid: null, originalDemandQuantity: 1, matchedQuantity: 0, unmatchedQuantity: 1, disposalTimestamp: 1, disposalSequence: "seq", demandStatus: "pending", proceedsTotal: 10, proceedsAllocationStatus: "fully_attributable", reasonCode: null };
assert.deepEqual(await repository.storeDemands([demand]), { demandsInserted: 1, existingDemands: 0 }); await repository.finalizeDemands([{ ...demand, matchedQuantity: 1, unmatchedQuantity: 0, demandStatus: "matched" }]);
const consumption = { id: "c1", fifoVersion: 1, sourceCostLotVersion: 1, sourceLedgerVersion: 1, disposalDemandId: "d1", sourceDisposalLedgerTransactionId: "t1", sourceDisposalLedgerLineId: "line1", sourceDisposalProjectionId: "p1", sourceDisposalCanonicalEventId: "c1", sourceLotId: "lot1", sourceLotGroupId: "group1", itemId: "1", itemUid: null, consumedQuantity: 1, disposalTimestamp: 1, disposalSequence: "seq", lotAcquisitionTimestamp: 0, lotAcquisitionSequence: "lot-seq", matchSequenceWithinDisposal: 0, matchSequenceWithinLot: 0, policyCode: "fungible-fifo", matchType: "fungible_fifo", basisStatus: "known_allocated_basis", consumedAllocatedBasis: 10, consumedUnitBasis: 10, sourceDisposalProceeds: 20 };
assert.deepEqual(await repository.storeConsumptions([consumption]), { consumptionsInserted: 1, existingConsumptions: 0 });
const replacementIds = await repository.prepareConsumptionReplacement(1, "1");
assert.equal(replacementIds.size, 0);
const replacementStatements = database.transactions.at(-1);
assert.match(replacementStatements[0].sql, /DELETE FROM accounting_fifo_consumptions WHERE fifo_version = \? AND item_id = \?/);
assert.deepEqual(replacementStatements[0].bind, [1, "1"]);
const disposition = { id: "fd1", fifoVersion: 1, sourceCostLotVersion: 1, sourceLedgerVersion: 1, sourceLedgerTransactionId: "t1", disposition: "fifo_consumed", reasonCode: "all_disposal_demand_matched" };
assert.deepEqual(await repository.storeDispositions([disposition]), { dispositionsInserted: 1, existingDispositions: 0 });
const sql = database.transactions.flat().map((statement) => statement.sql).join("\n"); assert.match(sql, /accounting_fifo_disposal_demands/); assert.match(sql, /accounting_fifo_consumptions/); assert.match(sql, /accounting_fifo_dispositions/);
await repository.listDerivedLotStates(1, 1, 10);
const lotInspectionQuery = database.queries.at(-1);
assert.doesNotMatch(lotInspectionQuery.sql, /GROUP BY l\.id/);
assert.match(lotInspectionQuery.sql, /WHERE l\.cost_lot_version = \?/);
assert.match(lotInspectionQuery.sql, /ORDER BY l\.acquisition_timestamp DESC, l\.acquisition_sequence DESC\s+LIMIT \?/);
assert.deepEqual(lotInspectionQuery.bind, [1, 1, 10]);
await repository.clearVersion(1); const clear = database.transactions.at(-1).map((statement) => statement.sql).join("\n"); assert.match(clear, /DELETE FROM accounting_fifo_consumptions/); assert.doesNotMatch(clear, /DELETE FROM accounting_cost_lots|DELETE FROM accounting_ledger_transactions/);
console.log("FIFO repository deterministic tests passed.");
